services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    # ports: [3333]
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3002:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules